### ISSUE TITLE
Design: Improve UX for information intake workflow

### ISSUE THREAD

**Issue by aswin1689** [homedepot/infinite-wish-board#114]
Current design to collect Child's information doesn't match with the new designs (background, fonts, UX) and the **Next** button's clickable area is too small.

**Feature Name** 
![image](https://user-images.githubusercontent.com/8471909/66353102-40b74c80-e92f-11e9-9c8c-9bae5123685e.png)

**Notes**
Any thoughts on if we should handle this in MVP?

**Comment by hellonoosh** [comment]
@aswin1689 Def MVP. Can you make the styling like the Landing Page? #98

**Comment by aswin1689** [comment]
Sure, I am working on it.

**Comment by WRMilling** [comment]
Closing now that #122 is merged.
