### ISSUE TITLE
Landing page redirects to Information collection page after typing first character in name/age field

### ISSUE THREAD

**Issue by aswin1689** [homedepot/infinite-wish-board#115]
**Summary:**
Landing page redirects to Information collection page after typing first character in name/age field

**Steps to Reproduce:**
1. Login to the app.
2. Click on any wish type card.
3. Enter a valid age
4. Enter a name. After you type the first character, you are redirected.

_second scenario_
1. Login to the app.
2. Click on any wish type card.
3. Enter a name
4. Enter 12 for age field. After you type the first character, you are redirected.

**Expected**
User should be able to type in the complete name.

**Actual**
User is redirected to the next page.

**Comment by WRMilling** [comment]
Fixed with #116, closing ticket.
