### ISSUE TITLE
Hitting `enter` on the wish details flow causes redirect to landing

### ISSUE THREAD

**Issue by WRMilling** [homedepot/infinite-wish-board#123]
**Summary:**

When you hit enter while filling in your wish details it redirects you to the landing page. 

**Expected Behavior**

Hitting enter should advance the user through the stepped workflow. 

**Actual Behavior**

User is redirected to the landing screen.

**Steps to Reproduce:**

1. Login
2. Enter name/age and select your wish type
3. Get to a step with a text field
4. Fill in text field and hit enter

**Notes:**

Edited 10/11/19 to add expectation behavior.

**Comment by ForiDunk** [comment]
Hi, I took a stab at this one

**Comment by WRMilling** [comment]
@ForiDunk Thanks for jumping on this, my apologies on the sparse bug report. I will detail a few more things on #124.

**Comment by vivekprabuTHD** [comment]
is this one done? i fixed it but, unable to push the branch i created

**Comment by ForiDunk** [comment]
@vivekprabuTHD I already fixed it, just needs review.

**Comment by WRMilling** [comment]
#124 addressed the initial ticket, closing. Thank you for your contribution @ForiDunk
