### ISSUE TITLE
Wish Curation List - data retrieval

### ISSUE THREAD

**Issue by connorjones13** [homedepot/infinite-wish-board#13]
Need to pull data from API to populate the list

**Comment by connorjones13** [comment]
working on this

**Comment by connorjones13** [comment]
https://github.com/homedepot/hackathon-purple-parrots/pull/21

**Comment by aclaire-thd** [comment]
Looks like this is already resolved by [pull request 21](https://github.com/homedepot/infinite-wish-board/pull/21)
