### ISSUE TITLE
[META] Rename this repo to reflect it is _the_ Make-a-Wish GA repo

### ISSUE THREAD

**Issue by crstamps2** [homedepot/infinite-wish-board#46]
`hackathon-purple-parrots`, while great for the hackathon, isn't so great branding wise for signifying this is where we will continue the work for this effort for Make-a-Wish.

**Comment by WRMilling** [comment]
@crstamps2 Definitely looking into doing this today/soon. What ideas do we have for a proper name @homedepot/purple-parrots ? 

Spitballing simpler ideas: 
wish-wall
make-a-wish-wall
infinite-wish-board (Playing off the Infinite Wish Award which is a recognition given to local chapters from the national organization).

**Comment by alex-hall** [comment]
The group likes infinite-wish-board
