### ISSUE TITLE
Wisher: Remove the condition question from the intake workflow

### ISSUE THREAD

**Issue by alex-hall** [homedepot/infinite-wish-board#54]
Remove condition question in the intake workflow

Currently, it is:
Hi CHILD_NAME, I have a few questions for you before we can make your wish come true!
Where are you from?
Tell us about your condition
Tell us more about your wish!

**Comment by crstamps2** [comment]
@alex-hall can you edit the issue to provide more context of what this is?

**Comment by alex-hall** [comment]
I've made this code change, but the current application asks what the child's condition is. We should talk to the make a wish folks, but they mentioned not capturing that information in the app, but rather offline with the parents

**Comment by aclaire-thd** [comment]
Note: The condition question doesn't require an answer (can just skip by clicking Next)

**Comment by crstamps2** [comment]
@alex-hall had some conversations with @hellonoosh about this. We are thinking about making it either "what hurts?" or just skip it all together, and let the parents/guardians add this information later.

**Comment by aashaypalliwar** [comment]
Can I work on this ?

**Comment by aclaire-thd** [comment]
Please do! Our contributing guidelines are here: https://github.com/homedepot/infinite-wish-board/blob/master/CONTRIBUTING.md

**Comment by WRMilling** [comment]
Resolved via #117.
