### ISSUE TITLE
Docs: Design Vision Needed

### ISSUE THREAD

**Issue by crstamps2** [homedepot/infinite-wish-board#63]
We need to post the design vision about how this whole thing is supposed look and feel and what the outcomes are. I am reaching out to design and PM colleagues I have, to help organize this project a little better.

**Comment by aclaire-thd** [comment]
What would be a good place in the repo for this?
Maybe [the UI readme](https://github.com/homedepot/infinite-wish-board/tree/master/ui)?

**Comment by aclaire-thd** [comment]
As of [PR 64](https://github.com/homedepot/infinite-wish-board/pull/64), we have a [docs folder](https://github.com/homedepot/infinite-wish-board/tree/master/documentation)
