### ISSUE TITLE
Login: Failed login could use a friendlier error message

### ISSUE THREAD

**Issue by aclaire-thd** [homedepot/infinite-wish-board#72]
Proposal to add friendly login message to to the site. 

**Feature Name** 
Failed login prompt

**Functionality**
When login fails, show have a human-friendly prompt

Attempt to login with invalid credentials
Current error message displayed is: Request failed with status code 401

**Notes:**
I'd recommend something like: Login failed. Please enter valid credentials. ?? (Not sure what product voice should be...)

**Comment by jacklagare** [comment]
I would like to work on this.

**Comment by aclaire-thd** [comment]
Hey Jack, we'd love to have you. Please follow the [contributing doc](https://github.com/homedepot/infinite-wish-board/blob/master/CONTRIBUTING.md) and reference this issue when making your pull request!

**Comment by tush38** [comment]
I would like to grab this.

**Comment by tush38** [comment]
![Capture](https://user-images.githubusercontent.com/52834521/66255245-23ec0f00-e79f-11e9-9079-58087e3f05b4.JPG)
I am getting this error on running the application.. Please help

**Comment by stevenwally** [comment]
Hi there! What's the status of this issue? I would be happy to pick it up if it has become stale :)

**Comment by aclaire-thd** [comment]
Hey @tush38 how's this going? Were you able to resolve the Docker error message?

**Comment by tush38** [comment]
Nope, still getting it. It also messed with my MongoDB setup!

**Comment by aclaire-thd** [comment]
In the master branch, a failed login now shows this message:
Incorrect username/password. Please try again.

Looks like we're covered here. Thanks for the help! :)
