### ISSUE TITLE
Wish Curation List: Search fails when there isn't an assigned sponsor

### ISSUE THREAD

**Issue by aclaire-thd** [homedepot/infinite-wish-board#79]
**Summary:**
Search fails when wish doesn't have a sponsor

**Steps to Reproduce:**
Create a wish
Skip adding a sponsor
On the wish list page, search for a phrase
Error displays: TypeError: undefined is not an object (evaluating 'wish.sponsor.name.toLowerCase')

Resolution: Check for null before trying to treat the value as a string
src/wishList/index.js:44
let wishItem = wish.child.name.toLowerCase() + wish.sponsor.name.toLowerCase() + wish.child.hometown.toLowerCase();

<img width="1030" alt="WishBoard-Search-FailsWhenNoSponsor" src="https://user-images.githubusercontent.com/48930585/66015383-50064800-e4a0-11e9-9df8-11b4927d386a.png">

**Notes:**
Although I haven't tried to save a wish without child name or child hometown, those values also might end up as null?

**Comment by liding987** [comment]
I start to work on it

**Comment by liding987** [comment]
working on this issue

**Comment by WRMilling** [comment]
Closing based on #117 being merged.
