### ISSUE TITLE
Styling: Update colors

### ISSUE THREAD

**Issue by aclaire-thd** [homedepot/infinite-wish-board#92]
Proposal to add update colors to to the site. 

**Feature Name** 
update colors

**Functionality**
Update the site colors to match the evolved design
"need to change some of the HEX# colours to match the new look and feel"

**Notes**
We will get input from design

**Comment by hellonoosh** [comment]
See https://github.com/homedepot/infinite-wish-board/issues/98

**Comment by crstamps2** [comment]
Moved to #98
