### ISSUE TITLE
Styling: update graphics

### ISSUE THREAD

**Issue by aclaire-thd** [homedepot/infinite-wish-board#97]
Proposal to add update graphics to to the site. 

**Feature Name** 
update graphics

**Functionality**
Update the site graphics to match the evolved design
[Colors update](https://github.com/homedepot/infinite-wish-board/issues/92) is a separate item

**Notes**
We will get input from design

**Comment by aclaire-thd** [comment]
Put updated graphics in [docs folder](https://github.com/homedepot/infinite-wish-board/tree/master/documentation)

**Comment by crstamps2** [comment]
moved to #98
