### ISSUE TITLE
Design: New landing page updates

### ISSUE THREAD

**Issue by crstamps2** [homedepot/infinite-wish-board#98]
After talks with M-a-W and the renovation team, we have some updated designs that match decals and stuff in the physical space. We need to update to match the below image.

Old page: 

<img width="854" alt="Screen Shot 2019-10-02 at 1 46 18 PM" src="https://user-images.githubusercontent.com/1142313/66068954-7ec20400-e51c-11e9-8ac5-80e4f4c42cb6.png">

New Page:

<img width="850" alt="Screen Shot 2019-10-02 at 1 39 59 PM" src="https://user-images.githubusercontent.com/1142313/66068974-82558b00-e51c-11e9-98b7-b72cd6d21d08.png">

**Comment by hellonoosh** [comment]
Revision | Asset
-- | --
1 | Change all Blue Text to Black | Hex# 000000
2 | Change blue outline to Black | Hex# 000000
3 | Change Magenta Text to Dark Orange Text | HEX# EE402E
4.1 | Switch to new GO GFX | icon_GO_100x100.svg
4.2 | Switch to new MEET GFX | icon_MEET_100x100.svg
4.3 | Switch to new BE GFX | icon_BE_100x100.svg
4.4 | Switch to new HAVE GFX | icon_HAVE_100x100.svg
5.1 | Remove Exclamation Mark. Add Arrow | icon_arrow_14x23.svg
5.2 | Remove Exclamation Mark. Add Arrow
5.3 | Remove Exclamation Mark. Add Arrow
5.4 | Remove Exclamation Mark. Add Arrow
6 | Revise Text "See" to Have" | HAVE
7 | Both the Graphic Icon AND the Text should be TAPABLE |  
8 | Switch out Blue Galaxy Logo to Black Galaxy Logi |

**Comment by hellonoosh** [comment]
Also, most all blue text on the intake form needs to be changed to black, please. I can pair, as needed. Just LMK.

**Comment by aclaire-thd** [comment]
Either we can keep these together as a design update or
use existing separate issues for
[color scheme update](https://github.com/homedepot/infinite-wish-board/issues/92)
[graphics/assets update](https://github.com/homedepot/infinite-wish-board/issues/97)

**Comment by crstamps2** [comment]
Seems like we are aligning more on this one, so I will close the others.

**Comment by crstamps2** [comment]
Here are the new assets needed: 

[new_assets.zip](https://github.com/homedepot/infinite-wish-board/files/3682960/new_assets.zip)

**Comment by jmfulgham** [comment]
Working on this now

**Comment by crstamps2** [comment]
Updated logos:

[logos.zip](https://github.com/homedepot/infinite-wish-board/files/3690458/logos.zip)

**Comment by hellonoosh** [comment]
MAW has revisions. See comps.
![MAW_Interface](https://user-images.githubusercontent.com/56089760/66244894-9e059080-e6d8-11e9-8c07-28b4748679a9.jpg)
![MAW_InterfaceButton](https://user-images.githubusercontent.com/56089760/66244895-9e059080-e6d8-11e9-9173-f6a71f509ff5.jpg)

**Comment by hellonoosh** [comment]
Here are the fonts they want want used.
[Document fonts.zip](https://github.com/homedepot/infinite-wish-board/files/3692566/Document.fonts.zip)

**Comment by hellonoosh** [comment]
Here is the new MAW Georgia Logo
![MAW_Georgia_RGB](https://user-images.githubusercontent.com/56089760/66245055-69460900-e6d9-11e9-9e72-e377b3f5275b.png)

**Comment by hellonoosh** [comment]
Here's is the background "starry space" pattern (optimized assuming this will also display of 4k HD TV. Let me know if its too big, loading too long, and needs sizing down for display on iPad.
[MAW_StarrySpace_Background.svg.zip](https://github.com/homedepot/infinite-wish-board/files/3692577/MAW_StarrySpace_Background.svg.zip)

**Comment by jmfulgham** [comment]
@hellonoosh Is there an updated Chevron.png that's black and not blue?

**Comment by liding987** [comment]
Is there anyone working on this issue? Otherwise, I can update the landing page.

**Comment by WRMilling** [comment]
@liding987 I believe @jmfulgham has a PR #107 running on this thread. 

Looks like we have a bit of a moving target. I am reviewing #107 now and this is what it currently looks like: 

<img width="878" alt="MAW Landing" src="https://user-images.githubusercontent.com/6162814/66668405-31801980-ec23-11e9-9d51-1eb4bde4bfc2.png">

@hellonoosh Do you have an update logo for the `The SKY is the limit` logo? 

@jmfulgham I believe the starry background asset is already on master if you need to reference it based on the most up to date images. Looks like we can ignore the chevron for now.

**Comment by WRMilling** [comment]
@crstamps2 @hellonoosh So that we can keep the PR train moving, do we want to settle on the comps from Noosh 7 days ago (Starry background revision) and open a new feature request for future revisions?

**Comment by crstamps2** [comment]
@WRMilling That works for me. We are showing this to some people come Monday, so if we want to go ahead and merge in what exists and open separate issues.

**Comment by crstamps2** [comment]
I can tackle changing the background.

**Comment by WRMilling** [comment]
@crstamps2 Sounds good. I will merge the current PR and open a new design update feature request with @hellonoosh's latest

**Comment by WRMilling** [comment]
Hey @hellonoosh, do you have `The SKY is the limit` image for the top right corner? I believe that is all #130 is waiting on.
